### ISSUE TITLE
The package versions for $HEALTHCLOUD_PACKAGE need to be manually edited for each [pre]release

### ISSUE THREAD

**Issue by tet3** [Appirio/Health-Cloud-Sfdx-Template#2]
The pre-release and released versions of the Healthcloud managed & unmanaged packages are hard-coded in `sfdx-project.json`:

 ```
   "packageAliases": {
    "HealthCloud@222": "04t1C000000Y1Qe",
    "HealthCloud@224": "04t1C000000Y1bD",
    "HealthCloud-UnmanagedExtension": "04tC0000001Eeby"
  },
```

So that now that Spring '20 is released, when I use `healthcloud start`, the Winter '20 version of the managed package gets installed, even though the scratch org is on Spring '20. Seems like this should be called out in the README at least. And if that needs to be done, it seems like the package alias suffixes should be some thing like `@released` and `@prerelease`. Then just the package Ids need to be updated.

(edited to reflect actual location of the package ids, the project file, not the bash script. My bad.)

**Comment by tet3** [comment]
Couldn't the released one in the `else` just not have an `@[version]` at all and be  
```
        HEALTHCLOUD_PACKAGE="HealthCloud"
```

**Comment by roarkely** [comment]
I'll update the README to reflect that. We are working to see if there is a dependable way to auto-retrieve the most recent package Ids, but for now we are coordinating with the Salesforce team to keep hard-coded values up-to-date as they go through their release cycles.

I think it makes since to keep the actual version numbers in the package aliases so that it is clear what we are referring to.
